import { hashSync } from "bcrypt-ts-edge";

const sampleData = {

  users:[
    {
      name:'John',
      email:"admin@example.com",
      password: hashSync('123456',10),
      role:'admin'
    },
    {
      name:'Jane',
      email:"user@example.com",
      password: hashSync('123456',10),
      role:'user'
    }
  ],

  products: [
    {
      name: 'Adidas Adizero Evo SL Black White',
      slug: 'adidas-adizero-evo-sl-black-white',
      category: 'Running Shoes',
      description: 'Lightweight road running shoe with a fast training profile and clean black-white finish.',
      images: [
        '/images/products/sasom/adidas-adizero-evo-sl-black-white-1.jpg',
        '/images/products/sasom/adidas-adizero-evo-sl-black-white-2.jpg',
      ],
      price: 149.99,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 24,
      stock: 12,
      isFeatured: true,
      banner: '/images/products/sasom/sasom-banner-1.webp',
    },
    {
      name: 'Adidas Adizero Boston 13 White Pink',
      slug: 'adidas-adizero-boston-13-white-pink',
      category: 'Running Shoes',
      description: 'Daily speed trainer with stable cushioning and a bright white, silver, and clear pink palette.',
      images: [
        '/images/products/sasom/adidas-adizero-boston-13-white-pink-1.jpg',
        '/images/products/sasom/adidas-adizero-boston-13-white-pink-2.jpg',
      ],
      price: 159.99,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 18,
      stock: 9,
      isFeatured: true,
      banner: '/images/products/sasom/sasom-banner-2.webp',
    },
    {
      name: 'Adidas Adizero SL2 Core Black Carbon',
      slug: 'adidas-adizero-sl2-core-black-carbon',
      category: 'Running Shoes',
      description: 'Responsive running shoe built for quick daily miles with a dark core black and carbon upper.',
      images: [
        '/images/products/sasom/adidas-adizero-sl2-black-carbon-1.jpg',
        '/images/products/sasom/adidas-adizero-sl2-black-carbon-2.jpg',
      ],
      price: 129.99,
      brand: 'Adidas',
      rating: 4.6,
      numReviews: 15,
      stock: 14,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Anta C202 Zone 2 Basic Black',
      slug: 'anta-c202-zone-2-basic-black',
      category: 'Running Shoes',
      description: 'Performance running model with a sculpted midsole and versatile basic black colorway.',
      images: [
        '/images/products/sasom/anta-c202-zone-2-basic-black-1.jpg',
        '/images/products/sasom/anta-c202-zone-2-basic-black-2.jpg',
      ],
      price: 119.99,
      brand: 'Anta',
      rating: 4.5,
      numReviews: 11,
      stock: 10,
      isFeatured: true,
      banner: '/images/products/sasom/sasom-banner-1.webp',
    },
    {
      name: 'Nike Air Max 95 OG Big Bubble Neon 2025',
      slug: 'nike-air-max-95-og-big-bubble-neon-2025',
      category: 'Lifestyle Sneakers',
      description: 'Iconic layered Air Max design with neon accents and visible cushioning underfoot.',
      images: [
        '/images/products/sasom/nike-air-max-95-neon-2025-1.jpg',
        '/images/products/sasom/nike-air-max-95-neon-2025-2.jpg',
      ],
      price: 189.99,
      brand: 'Nike',
      rating: 4.9,
      numReviews: 31,
      stock: 7,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Nike Air Max 97 Triple White Wolf Grey',
      slug: 'nike-air-max-97-triple-white-wolf-grey',
      category: 'Lifestyle Sneakers',
      description: 'Streamlined Air Max 97 silhouette with full-length cushioning and a clean white-grey build.',
      images: [
        '/images/products/sasom/nike-air-max-97-white-grey-1.jpg',
        '/images/products/sasom/nike-air-max-97-white-grey-2.jpg',
      ],
      price: 174.99,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 16,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'New Balance 1906 Silver Metallic Black White',
      slug: 'new-balance-1906-silver-metallic-black-white',
      category: 'Running Shoes',
      description: 'Retro-tech runner with a metallic silver mesh upper, black overlays, and supportive cushioning.',
      images: [
        '/images/products/sasom/new-balance-1906-silver-black-white-1.jpg',
        '/images/products/sasom/new-balance-1906-silver-black-white-2.jpg',
      ],
      price: 154.99,
      brand: 'New Balance',
      rating: 4.7,
      numReviews: 22,
      stock: 11,
      isFeatured: true,
      banner: '/images/products/sasom/sasom-banner-2.webp',
    },
    {
      name: 'New Balance 990v3 MiUSA Moonbeam',
      slug: 'new-balance-990v3-miusa-moonbeam',
      category: 'Lifestyle Sneakers',
      description: 'Premium Made in USA 990v3 with Teddy Santis styling and soft moonbeam neutral tones.',
      images: [
        '/images/products/sasom/new-balance-990v3-moonbeam-1.jpg',
        '/images/products/sasom/new-balance-990v3-moonbeam-2.jpg',
      ],
      price: 219.99,
      brand: 'New Balance',
      rating: 4.8,
      numReviews: 20,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'New Balance Dynasoft 900 V1 Summit White',
      slug: 'new-balance-dynasoft-900-v1-summit-white',
      category: 'Running Shoes',
      description: 'Comfortable daily trainer with Dynasoft cushioning and a bright summit white finish.',
      images: [
        '/images/products/sasom/new-balance-dynasoft-900-white-1.jpg',
        '/images/products/sasom/new-balance-dynasoft-900-white-2.jpg',
      ],
      price: 99.99,
      brand: 'New Balance',
      rating: 4.3,
      numReviews: 9,
      stock: 13,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Asics Gel-Sonoma 15-50 Feather Grey',
      slug: 'asics-gel-sonoma-15-50-feather-grey',
      category: 'Trail Shoes',
      description: 'Trail-inspired Asics silhouette with GEL comfort and feather grey wood crepe color blocking.',
      images: [
        '/images/products/sasom/asics-gel-sonoma-grey-wood-crepe-1.webp',
        '/images/products/sasom/asics-gel-sonoma-grey-wood-crepe-2.webp',
      ],
      price: 124.99,
      brand: 'Asics',
      rating: 4.5,
      numReviews: 13,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Asics Skyhand OG Dark Neptune Violet',
      slug: 'asics-skyhand-og-dark-neptune-violet',
      category: 'Training Shoes',
      description: 'Low-profile sport sneaker with heritage court DNA and dark neptune violet accents.',
      images: [
        '/images/products/sasom/asics-skyhand-og-dark-neptune-1.jpg',
        '/images/products/sasom/asics-skyhand-og-dark-neptune-2.jpg',
      ],
      price: 109.99,
      brand: 'Asics',
      rating: 4.4,
      numReviews: 8,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Adidas Samba OG Cloud White Shock Cyan',
      slug: 'adidas-samba-og-cloud-white-shock-cyan',
      category: 'Lifestyle Sneakers',
      description: 'Classic Samba OG profile with cloud white leather, gum tooling, and shock cyan details.',
      images: [
        '/images/products/sasom/adidas-samba-og-white-cyan-1.jpg',
        '/images/products/sasom/adidas-samba-og-white-cyan-2.jpg',
      ],
      price: 119.99,
      brand: 'Adidas',
      rating: 4.6,
      numReviews: 19,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Vans Authentic Black Canvas',
      slug: 'vans-authentic-black-canvas',
      category: 'Lifestyle Sneakers',
      description: 'Minimal low-top canvas sneaker with a durable rubber outsole and all-black styling.',
      images: [
        '/images/products/sasom/vans-authentic-black-1.jpg',
        '/images/products/sasom/vans-authentic-black-2.jpg',
      ],
      price: 64.99,
      brand: 'Vans',
      rating: 4.2,
      numReviews: 14,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Vans Classic Slip-On Checkerboard',
      slug: 'vans-classic-slip-on-checkerboard',
      category: 'Lifestyle Sneakers',
      description: 'Easy slip-on sneaker with classic checkerboard pattern and everyday skate-inspired comfort.',
      images: [
        '/images/products/sasom/vans-slip-on-checkerboard-1.jpg',
        '/images/products/sasom/vans-slip-on-checkerboard-2.jpg',
      ],
      price: 69.99,
      brand: 'Vans',
      rating: 4.3,
      numReviews: 17,
      stock: 16,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Crocs Classic Platform Blue',
      slug: 'crocs-classic-platform-blue',
      category: 'Clogs',
      description: 'Lightweight platform clog with signature Crocs comfort and a bold blue women’s colorway.',
      images: [
        '/images/products/sasom/crocs-platform-blue-1.jpg',
        '/images/products/sasom/crocs-platform-blue-2.jpg',
      ],
      price: 74.99,
      brand: 'Crocs',
      rating: 4.1,
      numReviews: 7,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
